-- 기존 6개 테이블 생성 후 SQL Editor에서 전체 실행 (기록 삭제 없음).
begin;
alter table public.messages add column if not exists sort_order bigint generated by default as identity;
create index if not exists messages_order_idx on public.messages(user_id, session_id, timestamp, sort_order);
create table if not exists public.legacy_feedbacks (
    user_id uuid not null references auth.users(id) on delete cascade,
    id bigint not null,
    message_id text not null,
    session_id text,
    rating integer not null,
    feedback_text text,
    created_at timestamptz not null,
    primary key(user_id, id)
);
alter table public.legacy_feedbacks enable row level security;
revoke all on public.legacy_feedbacks from public, anon, authenticated;
grant select on public.legacy_feedbacks to authenticated;
drop policy if exists owner_read on public.legacy_feedbacks;
create policy owner_read on public.legacy_feedbacks for select to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.save_chat_turn(
    p_user_message text, p_assistant_message text, p_session text,
    p_user_text text, p_assistant_text text, p_elapsed double precision
) returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
    existing_user public.messages;
    existing_assistant public.messages;
    ts timestamptz := clock_timestamp();
begin
    perform 1 from public.sessions where user_id=auth.uid() and session_id=p_session for update;
    if not found then raise exception 'Session not found'; end if;
    select * into existing_user from public.messages where user_id=auth.uid() and id=p_user_message;
    if found then
        select * into existing_assistant from public.messages where user_id=auth.uid() and id=p_assistant_message;
        if existing_user.session_id <> p_session or existing_user.role <> 'user'
           or existing_user.content <> p_user_text or existing_assistant.id is null
           or existing_assistant.session_id <> p_session or existing_assistant.role <> 'assistant' then
            raise exception 'Request ID conflict' using errcode='23505';
        end if;
        return jsonb_build_object('content', existing_assistant.content, 'created', false);
    end if;
    insert into public.messages(user_id,id,session_id,role,content,timestamp,response_time_sec)
    values (auth.uid(),p_user_message,p_session,'user',p_user_text,ts,null),
           (auth.uid(),p_assistant_message,p_session,'assistant',p_assistant_text,ts+interval '1 microsecond',p_elapsed);
    update public.sessions set updated_at=ts where user_id=auth.uid() and session_id=p_session;
    return jsonb_build_object('content', p_assistant_text, 'created', true);
end $$;

create or replace function public.practice_memories(p_limit integer default 3)
returns setof public.user_memories language sql security invoker set search_path='' as $$
    select * from public.user_memories where user_id=auth.uid()
      and corrected_text is not null and corrected_text <> ''
      and (next_review_at is null or next_review_at <= now())
    order by next_review_at asc nulls first, created_at desc, id desc limit greatest(0,least(p_limit,20));
$$;

create or replace function public.review_memory(p_id bigint, p_remembered boolean)
returns boolean language plpgsql security invoker set search_path='' as $$
begin
    update public.user_memories set review_count=review_count+1,
      next_review_at=now()+case when p_remembered then interval '7 days' else interval '1 day' end
    where user_id=auth.uid() and id=p_id;
    return found;
end $$;

create table if not exists public.ai_usage (
    user_id uuid not null references auth.users(id) on delete cascade,
    usage_day date not null,
    calls integer not null default 0,
    primary key(user_id,usage_day)
);
alter table public.ai_usage enable row level security;
revoke all on public.ai_usage from public,anon,authenticated;
grant select on public.ai_usage to authenticated;
drop policy if exists owner_read on public.ai_usage;
create policy owner_read on public.ai_usage for select to authenticated using ((select auth.uid())=user_id);

-- Only consumes quota; clients cannot reset or raise their own limit.
create or replace function public.consume_ai_usage()
returns boolean language plpgsql security definer set search_path='' as $$
declare changed integer;
begin
    if auth.uid() is null then return false; end if;
    insert into public.ai_usage(user_id,usage_day,calls)
    values(auth.uid(),(now() at time zone 'Asia/Seoul')::date,1)
    on conflict(user_id,usage_day) do update set calls=public.ai_usage.calls+1
    where public.ai_usage.calls<100;
    get diagnostics changed = row_count;
    return changed=1;
end $$;

revoke all on function public.save_chat_turn(text,text,text,text,text,double precision),
    public.practice_memories(integer), public.review_memory(bigint,boolean),
    public.consume_ai_usage() from public,anon,authenticated;
grant execute on function public.save_chat_turn(text,text,text,text,text,double precision),
    public.practice_memories(integer), public.review_memory(bigint,boolean),
    public.consume_ai_usage() to authenticated;
notify pgrst, 'reload schema';
commit;
