-- 대화 기록을 삭제하지 않고 메시지 순서 열을 보완합니다.
begin;
alter table public.messages
    add column if not exists sort_order bigint generated by default as identity;
create index if not exists messages_order_idx
    on public.messages(user_id, session_id, timestamp, sort_order);
notify pgrst, 'reload schema';
commit;

select column_name from information_schema.columns
where table_schema = 'public' and table_name = 'messages' and column_name = 'sort_order';
