-- Supabase SQL Editor에 이 파일 전체를 붙여넣고 한 번 실행하세요.
-- 새 프로젝트용: 같은 이름의 테이블이 있으면 덮어쓰지 않고 중단합니다.
-- 테이블과 접근 규칙만 생성합니다. SQLite 기록 이전은 별도 작업입니다.
begin;

create table public.sessions (
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    session_id text not null,
    title text not null,
    partner_name text not null,
    difficulty text not null,
    topic text not null,
    roleplay_id text,
    roleplay_args jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, session_id)
);

create table public.messages (
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    id text not null,
    session_id text not null,
    role text not null,
    content text not null,
    translation text,
    furigana text,
    response_time_sec double precision,
    quality_score double precision,
    timestamp timestamptz not null default now(),
    primary key (user_id, id),
    unique (user_id, session_id, id),
    foreign key (user_id, session_id)
        references public.sessions(user_id, session_id) on delete cascade
);

create table public.user_memories (
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    id bigint generated by default as identity,
    category text not null,
    original_text text,
    corrected_text text,
    explanation text,
    created_at timestamptz not null default now(),
    next_review_at timestamptz,
    review_count integer not null default 0 check (review_count >= 0),
    primary key (user_id, id)
);

create table public.session_summaries (
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    session_id text not null,
    summary_text text not null,
    updated_at timestamptz not null default now(),
    primary key (user_id, session_id),
    foreign key (user_id, session_id)
        references public.sessions(user_id, session_id) on delete cascade
);

create table public.user_facts (
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    id bigint generated by default as identity,
    fact_key text,
    fact_value text not null,
    updated_at timestamptz not null default now(),
    primary key (user_id, id),
    unique (user_id, fact_key)
);

create table public.message_feedbacks (
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    id bigint generated by default as identity,
    message_id text not null,
    session_id text,
    rating integer not null,
    feedback_text text,
    created_at timestamptz not null default now(),
    primary key (user_id, id),
    unique (user_id, message_id),
    foreign key (user_id, message_id)
        references public.messages(user_id, id) on delete cascade,
    foreign key (user_id, session_id, message_id)
        references public.messages(user_id, session_id, id) on delete cascade
);

create index sessions_recent_idx on public.sessions(user_id, updated_at desc);
create index messages_conversation_idx on public.messages(user_id, session_id, timestamp);
create index memories_due_idx on public.user_memories(user_id, next_review_at);

-- 모든 테이블에 소유자 확인 규칙을 적용합니다.
-- user_id는 로그인한 사용자의 ID와 일치해야 합니다.
do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'sessions', 'messages', 'user_memories',
        'session_summaries', 'user_facts', 'message_feedbacks'
    ] loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format('revoke all on table public.%I from public, anon, authenticated', table_name);
        execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
        execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
        execute format(
            'create policy owner_select on public.%I for select to authenticated using ((select auth.uid()) = user_id)',
            table_name);
        execute format(
            'create policy owner_insert on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',
            table_name);
        execute format(
            'create policy owner_update on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
            table_name);
        execute format(
            'create policy owner_delete on public.%I for delete to authenticated using ((select auth.uid()) = user_id)',
            table_name);
    end loop;
end $$;

grant usage on schema public to authenticated, service_role;
revoke all on sequence public.user_memories_id_seq,
    public.user_facts_id_seq, public.message_feedbacks_id_seq
    from public, anon, authenticated;
grant usage on sequence public.user_memories_id_seq,
    public.user_facts_id_seq, public.message_feedbacks_id_seq to authenticated;
grant usage, select, update on sequence public.user_memories_id_seq,
    public.user_facts_id_seq, public.message_feedbacks_id_seq to service_role;

commit;
